const images = {
    Logo : require("src/assets/images/Logo.png"),
    LogoGif : require("src/assets/images/LoadingNew.gif"),
    LeftArrow : require("src/assets/images/LeftArrow.png"),
    RightChev : require("src/assets/images/RightChev.png"),
    LogoBackground : require("src/assets/images/LogoBackground.png"),
    OnBoardingOne : require("src/assets/images/OnBoardingOne.png"),
    OnBoardingTwo : require("src/assets/images/OnBoardingTwo.png"),
    OnBoardingThree : require("src/assets/images/OnBoardingThree.png"),
    PasswordEye : require("src/assets/images/PasswordEye.png"),
    EyeOpen : require("src/assets/images/EyeOpen.png"),
    Google : require("src/assets/images/Google.png"),
    Facebook : require("src/assets/images/Facebook.png"),
    Checked : require("src/assets/images/Checked.png"),
    DropDown : require("src/assets/images/DropDown.png"),
    PickupLocation : require("src/assets/images/PickupLocation.png"),
    Location : require("src/assets/images/Location.png"),
    Home : require("src/assets/images/Home.png"),
    ArrowRight : require("src/assets/images/ArrowRight.png"),
    Delete : require("src/assets/images/Delete.png"),
    Menu : require("src/assets/images/Menu.png"),
    User : require("src/assets/images/User.png"),
    Language : require("src/assets/images/Language.png"),
    Help : require("src/assets/images/Help.png"),
    Setting : require("src/assets/images/Setting.png"),
    Faqs : require("src/assets/images/Faqs.png"),
    Logout : require("src/assets/images/Logout.png"),
    Plus : require("src/assets/images/Plus.png"),
    MapImage : require("src/assets/images/MapImage.png"),
    PhoneIcon : require("src/assets/images/PhoneIcon.png"),
    WagonLogo : require("src/assets/images/WagonLogo.png"),
    DownChev : require("src/assets/images/DownChev.png"),
    UpChev : require("src/assets/images/UpChev.png"),
    Privacy : require("src/assets/images/Privacy.png"),
    EditProfile : require("src/assets/images/EditProfile.png"),
    LogoutIcon : require("src/assets/images/LogoutIcon.png"),
    Aboutus : require("src/assets/images/Aboutus.png"),
    EditPencil : require("src/assets/images/EditPencil.png"),
    Camera : require("src/assets/images/Camera.png"),
    
}

export default images